### ISSUE TITLE
Extract Kitura related folders to a separate repo.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Package-Builder#1]
- [x]  As the intention of this repo is to have a package-builder that is not tied to any Kitura repos in specific (i.e. this is a builder for any of our Swift repos, Kitura related or not), let's move the following folders to a separate single repo named `Kitura-CI`:
- Kitura-Session-Redis
- Kitura-redis

Also, to avoid breaking the dependent repos, we will have to keep the above folders in place until the PRs have been merged/accepted.
- [ ] As part of this task, we will need to perform a couple of PRs against the dependent repos (i.e. dependent repos will add as git submodules the new repo that will contain the above folders) and will also need to come up with a convention so that the build scripts in this repo can dynamically find the above folders.
- [x] Once all PRs are merged, we should come back and clean up this repo (i.e., remove correspoding folders from it).

**Comment by BDHernand** [comment]
The design i'm thinking for the remainder of the work is as follows:
1.  in the travis file for the 2 repos in questions, export a {VARIABLE_TO_USE} that points to where their test scripts are located.

export VARIABLE_TO_USE=$TRAVIS_BUILD_DIR/Kitura-CI/Kitura-redis
1.  In the Package-Builder code change build-package.sh as follows:

<sample line>
sourceScript "${projectFolder}/Kitura-CI/${projectName}/common/after_tests.sh" ">> Completed common post-tests steps."
<change to>
sourceScript "${VARIABLE_TO_USE}/common/after_tests.sh" ">> Completed common post-tests steps."

Im thinking of using the variable name as REPO_TEST_SCRIPTS_DIR or repoTestScriptDir.  Leaning towards repoTestScriptDir.

**Comment by BDHernand** [comment]
This should completely remove any kitiura references from the package builder code and make it generic

**Comment by rolivieri** [comment]
@BDHernand Can you try the following instead?

```
find ${projectFolder} -path "*/${projectName}/${osName}/before_tests.sh"
<if found, source it…>

find ${projectFolder} -path "*/${projectName}/common/before_tests.sh"
<if found, source it…>
```

And so forth for the other ones (e.g. `after_tests.sh`)

In other words, if the `find` command finds the file we are looking for in the expected relative path, let’s then source it… 

The only drawback I see with this approach is that there is the possibility of a project/repo having a file that matches our convention but not meant to be used by PackageBuilder. This is a minor risk though… I doubt we will run into it… but if we do, we can address it at that time. At least this approach won’t require any new parameters or global variables and leverages a convention that we can expect projects that use PackageBuilder to follow.

**Comment by BDHernand** [comment]
@rolivieri  please review the latest code in the PR.  Simplified it to remove all Kitura references

**Comment by rolivieri** [comment]
@BDHernand Thanks, looks good. Any additional testing you need to complete? If you are done I can go ahead and merge the PR. Let me know.
