### ISSUE TITLE
install_swift_binaries.sh breaks ubuntu 16.04 build

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/Package-Builder#104]
```
export PATH=`echo ${PATH} | awk -v RS=: -v ORS=: '/clang/ {next} {print}'`
```
The above line in [install_swift_binaries.sh](https://github.com/IBM-Swift/Package-Builder/blob/master/linux/install_swift_binaries.sh#L34) adds a newline and extra colon at the end of PATH and causes some commands to no longer be available. It also doesn't seem to change the path in any other way in ubuntu 14.04 or 16.04, so not sure it's serving a purpose at all.

For example, it changes PATH from:
```
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```
to:
```
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
:"
```
Commenting out this line seems to fix the issue for Kitura, but not sure if it does anything useful on other builds. Could we either fix or remove this line.

**Comment by rolivieri** [comment]
We should not need that line (34) anymore since we commented out lines 37-38. We should be able to comment it out without any side effects.

@christiancompton As part of the changes you are currently working on, can you comment out line 34 and test that what we have now in our code still works just fine?

**Comment by na-gupta** [comment]
Not sure it matters, but line 34 doesn't seem to be changing the path at all except for mangling it. It's looking for the pattern `/clang/` in PATH, but that pattern is never in PATH (`/usr/bin/` is the PATH segment that causes `/usr/bin/clang` to be found). So line 34 might be irrelevant regardless of lines 37-38.

**Comment by christiancompton** [comment]
This code is now in Develop: https://github.com/IBM-Swift/Package-Builder/commit/2c3430085e5fdf378989edcba05d4ae7d8a92d72

https://github.com/IBM-Swift/Package-Builder/pull/102

**Comment by christiancompton** [comment]
@na-gupta - This code is now in master: https://github.com/IBM-Swift/Package-Builder/pull/102

**Comment by na-gupta** [comment]
Thank you!
