### ISSUE TITLE
Swift 4 Snapshot Breaking Codecov Portion

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Package-Builder#111]
Just FYI in case this change ends up in the final Swift 4 release: SPM changed how the Xcode scheme is named in Swift 4 (as observed in 06/11 toolchain).

Travis log:
https://travis-ci.org/IBM-Swift/swift-html-entities/jobs/242539038#L342

Previously, the scheme name was the same as the package name: `HTMLEntities`.
With the 06/10 toolchain, the scheme name is now `HTMLEntities-Package`. I checked this by generating xcodeproj locally using the 06/11 toolchain.

```
ylin@youming-mbpr:~/Swift/swift-html-entities$ xcodebuild -list
Information about project "HTMLEntities":
    Targets:
        HTMLEntitiesTests
        HTMLEntities
        HTMLEntitiesPackageTests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Debug" is used.

    Schemes:
        HTMLEntities-Package
        HTMLEntitiesPackageTests
```

**Comment by djones6** [comment]
This appears to have been reverted before the Swift 4 release.  Current builds do not have this change.
