### ISSUE TITLE
Clean up code once we stop supporting swift versions prior to Swift 3.0 GA.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Package-Builder#12]

**Comment by BDHernand** [comment]
also removing some unneeded apt-get packages.  Robert suggested it.  I did a travis build and everything worked.

**Comment by rolivieri** [comment]
@BDHernand - To complete validation, let's build Kitura-net using these latest changes.

**Comment by rolivieri** [comment]
@BDHernand I just saw the comparison logic included in the snippet of code below (`build_package.sh`), which we had added to support an older version of Swift (08/07). We can remove the comparison test logic since we are not supporting versions prior to Swift 3.0. Hence, re-opening this task.

```
# Execute test cases
if [ -e "${projectFolder}/Tests" ]; then
    echo ">> Testing Swift package..."
    if [[ $SWIFT_SNAPSHOT == *"08-07"* ]]; then
       swift test -Xcc -fblocks
    else
       swift test
    fi
    echo ">> Finished testing Swift package."
    echo
else
    echo ">> No testcases exist..."
fi
```
