### ISSUE TITLE
`swift test -Xcc -fblocks` breaks 0725 CI

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Package-Builder#13]
https://travis-ci.org/IBM-Swift/Kitura-net/jobs/155085642

Looks like this option can only be used on 0807 snapshot.

**Comment by ianpartridge** [comment]
@rolivieri @BDHernand we should probably revert this until we have support for switchable snapshots.

**Comment by rolivieri** [comment]
@BDHernand Can you make this a priority today?

if swift binary is 0807 
   then swift test -Xcc -fblocks
   else swift test
