### ISSUE TITLE
Can't get codecov to work

### ISSUE THREAD

**Issue by ladislas** [IBM-Swift/Package-Builder#142]
Hi there!

First, thanks a lot for this great tool that makes running CI super easy for SPM Packages.

Even though everything builds well and tests pass, I can't seem to get codecov to work.

The build log says it has uploaded the reports to Codecov.io but when I want to see them it tells me that there was some errors in the reports...

Here are the relevant links:

- github repo: https://github.com/ladislas/SwiftyBinarySearch
- .travis.yml: https://github.com/ladislas/SwiftyBinarySearch/blob/develop/.travis.yml
- travis CI: https://travis-ci.org/ladislas/SwiftyBinarySearch/builds/433952814
- codecov: https://codecov.io/github/ladislas/SwiftyBinarySearch/commit/0559ff96dbcff8be9d773531c514cf48400043e0

I'm using Xcode 10 and Swift 4.2 on my machine and on Travis.

Thanks in advance!

Best,  
-- Ladislas

**Comment by ianpartridge** [comment]
I'm afraid I can't see your CodeCov report.  Could you paste the errors you are seeing?

**Comment by ladislas** [comment]
Yes, I've removed everything since I'm now using Sonarcloud.
Codecov was just saying that there was an error processing the files but without more information.

I'm closing the issue.
