### ISSUE TITLE
Rename KITURA_CI_BUILD_SCRIPTS_DIR to BUILDER_SCRIPTS_DIR.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Package-Builder#18]
See contents of the Package-Builder/build/Makefile file.

**Comment by rolivieri** [comment]
This also requires updating the Makefile that exists in the dependent repos... therefore, it will require a series of PRs.

**Comment by BDHernand** [comment]
Ok all our repo's are updated.  Waiting on 3 PR's from on the Kitura repos
