### ISSUE TITLE
Support SwiftLint

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Package-Builder#22]
We'd like to automatically run SwiftLint against PRs on Travis.  Would it be possible for this to be done via Package-Builder?

**Comment by rolivieri** [comment]
This should be possible. We will look into it hopefully soon.

Though this would occur for all builds, regardless if it is a PR or not.

**Comment by ianpartridge** [comment]
That's fine - thanks @rolivieri

**Comment by rolivieri** [comment]
@BDHernand Here's the link: https://github.com/realm/SwiftLint. There's already a swiftlint file in the PackageBuilder repo.

**Comment by rolivieri** [comment]
@ianpartridge We noticed there is a swiftlint file in some of the Kitura repos. I had thought the purpose of having the swiftlint file in the PackageBuilder repo was 1) to avoid having to check in a swiftlint file in every Kitura repo and 2) to ensure that the same set of rules (in the single swiftlint file) is applied to all Kitura repos. Has this changed? Are you guys planning on using a different approach?

**Comment by ianpartridge** [comment]
We'd like to remove the swiftlint files from Kitura repos and use a common file in PackageBuilder.

**Comment by BDHernand** [comment]
@ianpartridge i started to enable swiftlint in package builder and have it pointed to the .swiftlint.yml file in the Package-Builder directory.  I was using my Forked version of Kitura which I had did a pull from the master branch to bring it up to date.  I got the following from swiftlint

Done linting! Found 632 violations, 12 serious in 54 files.

**Comment by BDHernand** [comment]
@ianpartridge should the .swiftlint file be changed or is it good to go?

**Comment by BDHernand** [comment]
I ran it again locally with the .swiftlint.ym file in the Kitura directory and got

Done linting! Found 2573 violations, 83 serious in 115 files.

which swiftlint file should we use?

**Comment by ianpartridge** [comment]
We should use the one in `Package-Builder`. We still need to go through and fix the violations which couldn't be fixed by the auto-correcter.

I've deleted the one in `Kitura`.

Thanks!

**Comment by BDHernand** [comment]
Some of the issues we are having with swiftlint is the following:

line_length:  Some test files have JSON strings that are over a certain length producing errors being returned.  These are mainly in the test files.  Should we exclude these in the swiftlint.yml file?

cyclomatic_complexity:  Some files have a lot of case statement/if checks in the functions which are causing errors in swiftlint.  Currently if it is more than X it will error out

function_parameter_count: if it is more than 5 swiftlint errors out

**Comment by BDHernand** [comment]
some changes that are going to be added to the functionality:
1.  Only the Sources directory will be linted.
2.  If the root repo directory contains a .swiftlint.yml file then the package builder will use that to override the default rule file located in package builder.  This will give the repo owner the ability to disable some lint rules that they may not be able to correct without breaking people.

**Comment by ianpartridge** [comment]
line_length: Yes, let's exclude these files

cyclomatic_complexity: Exclude this test?

function_parameter_count: What's the list of functions that error? We should review them.

**Comment by BDHernand** [comment]
@ianpartridge we change the package builder swift lint yml file for line length to give a warning after 250 and error out after 500 characters.  We have not disabled the cyclomatic_complexity or the function_parameter_count

**Comment by BDHernand** [comment]
@ianpartridge do you have an ETA on the Kitura repositories being ready for us to merge the swiftlint branch into master?
