### ISSUE TITLE
Ability to have custom builds for linux and macOS.

### ISSUE THREAD

**Issue by BDHernand** [IBM-Swift/Package-Builder#28]
Need the ability for a Repo to specify a custom build file for linux and mac.

if the repo specifies a .swift-build-linux or .swift-build-macOS then need to run the command 
listed in that file vs the swift build command that we normally use.

**Comment by BDHernand** [comment]
https://github.com/IBM-Swift/Package-Builder/pull/27

is for this issue

**Comment by rolivieri** [comment]
- [ ] As part of this, you may not need this flag anymore for linux: "-Xcc -fblocks". I just removed this from the buildpack and tested it.

**Comment by BDHernand** [comment]
@rolivieri PR is done and assigned to you
