### ISSUE TITLE
Parameterize testing credentials repo

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Package-Builder#30]
In `build-package.sh`, we have the name of the testing credentials folder hardcoded to `Kitura-TestingCredentials`. Instead, this should be an optional parameterized value coming from the travis.yml file. We should then update the `build-package.sh` script accordingly. Note that this change will require **PRs** against the dependent repos.

**Comment by BDHernand** [comment]
@rolivieri Shmuel merged my PR.  We can do a code review on the parameterize branch

**Comment by rolivieri** [comment]
@BDHernand Just saw this. It looks good. Feel free merge this PR, thanks!
