### ISSUE TITLE
Remove branch parameter from build_package.sh file.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Package-Builder#38]
This implies also updating the `.travis.yml` files in all repos.

**Comment by BDHernand** [comment]
- [x] [Swift-cfenv](https://github.com/IBM-Swift/Swift-cfenv)
- [x] [swift-helloworld](https://github.com/IBM-Bluemix/swift-helloworld)
- [x] swift-helloworld estado branch 
- [x] [Kitura-Starter](https://github.com/IBM-Bluemix/Kitura-Starter)
- [x] [Swift-Cloudant-Boilerplate](https://github.com/IBM-Swift/Swift-Cloudant-Boilerplate)
- [x] [cf-deployment-tracker-client-swift](https://github.com/IBM-Bluemix/cf-deployment-tracker-client-swift)
- [x] [BluePic](https://github.com/IBM-Swift/BluePic) 

## Owned by other team members:

## Core repositories:
- [x] [Kitura](https://github.com/IBM-Swift/Kitura)
- [x] [Kitura-net](https://github.com/IBM-Swift/Kitura-net)
- [x] [SwiftyJSON](https://github.com/IBM-Swift/SwiftyJSON)

## Sample applications:
- [x] [Kitura-Sample](https://github.com/IBM-Swift/Kitura-Sample)

## Logging:
- [x] [HeliumLogger](https://github.com/IBM-Swift/HeliumLogger)

## Credentials:
- [x] [Kitura-Credentials](https://github.com/IBM-Swift/Kitura-Credentials)
- [x] [Kitura-CredentialsFacebook](https://github.com/IBM-Swift/Kitura-CredentialsFacebook)
- [x] [Kitura-CredentialsGitHub](https://github.com/IBM-Swift/Kitura-CredentialsGitHub)
- [x] [Kitura-CredentialsGoogle](https://github.com/IBM-Swift/Kitura-CredentialsGoogle)
- [x] [Kitura-CredentialsHTTP](https://github.com/IBM-Swift/Kitura-CredentialsHTTP)
- [x] [Kitura-Credentials-Sample](https://github.com/IBM-Swift/Kitura-Credentials-Sample)

## Sessions:
- [x] [Kitura-Session](https://github.com/IBM-Swift/Kitura-Session)
- [x] [Kitura-Session-Redis](https://github.com/IBM-Swift/Kitura-Session-Redis)

## Backend drivers:
- [x] [Kitura-CouchDB](https://github.com/IBM-Swift/Kitura-CouchDB)
- [x] [Kitura-redis](https://github.com/IBM-Swift/Kitura-redis)

## Templating:
- [x] [Kitura-SampleStencil](https://github.com/IBM-Swift/Kitura-SampleStencil)

## Middlewares:
- [x] [Kitura-Cache](https://github.com/IBM-Swift/Kitura-Cache)
- [x] [Kitura-Compression](https://github.com/IBM-Swift/Kitura-Compression)
- [x] [Kitura-CORS](https://github.com/IBM-Swift/Kitura-CORS)
- [x] [Kitura-CSRF](https://github.com/IBM-Swift/Kitura-CSRF)

## Bridging:
- [x] [Bridging](https://github.com/IBM-Swift/Bridging)

## Experimental:
- [x] [Kitura-Request](https://github.com/IBM-Swift/Kitura-Request)
- [x] [BlueSocket](https://github.com/IBM-Swift/BlueSocket)
- [x] [BlueSSLService](https://github.com/IBM-Swift/BlueSSLService)
- [x] [BlueCryptor](https://github.com/IBM-Swift/BlueCryptor)

## Repos not using PackageBuilder but are not owned by DevOps:
- [LoggerAPI](https://github.com/IBM-Swift/LoggerAPI)
- [Kitura-MustacheTemplateEngine](https://github.com/IBM-Swift/Kitura-MustacheTemplateEngine)
- [Kitura-StencilTemplateEngine](https://github.com/IBM-Swift/Kitura-StencilTemplateEngine)
- [Kitura-TemplateEngine](https://github.com/IBM-Swift/Kitura-TemplateEngine)
- [Kitura-ResponseTime](https://github.com/IBM-Swift/Kitura-ResponseTime)
- [Swift-Kuery](https://github.com/IBM-Swift/Swift-Kuery)

## Repos not using PackageBuilder but are owned by DevOps:
- [kitura-ubuntu-docker](https://github.com/IBM-Swift/kitura-ubuntu-docker)
- [swift-ubuntu-docker](https://github.com/IBM-Swift/swift-ubuntu-docker)
- [Package-Builder](https://github.com/IBM-Swift/Package-Builder)
- [swift-buildpack](https://github.com/IBM-Swift/swift-buildpack)

This must be done before enabling swiftlint on PackageBuilder (see https://github.com/IBM-Swift/Package-Builder/issues/22).
