### ISSUE TITLE
***-PREVIEW Swift toolchains not supported

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Package-Builder#40]
From [Travis log](https://travis-ci.org/IBM-Swift/SwiftyJSON/jobs/167081518):

```
echo ">> Installing '${SWIFT_SNAPSHOT}'..."
>> Installing 'swift-3.0.1-PREVIEW-3-RELEASE'...
# Install Swift compiler
cd $WORK_DIR
wget https://swift.org/builds/$SNAPSHOT_TYPE/$UBUNTU_VERSION_NO_DOTS/$SWIFT_SNAPSHOT/$SWIFT_SNAPSHOT-$UBUNTU_VERSION.tar.gz
--2016-10-12 15:02:47--  https://swift.org/builds/swift-3.0.1-preview-3-release/ubuntu1404/swift-3.0.1-PREVIEW-3-RELEASE/swift-3.0.1-PREVIEW-3-RELEASE-ubuntu14.04.tar.gz
Resolving swift.org (swift.org)... 169.45.67.140
Connecting to swift.org (swift.org)|169.45.67.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-10-12 15:02:47 ERROR 404: Not Found.
```

The correct download URL is `https://swift.org/builds/swift-3.0.1-preview-3/ubuntu1404/swift-3.0.1-PREVIEW-3/swift-3.0.1-PREVIEW-3-ubuntu14.04.tar.gz`; there is no `-RELEASE` after `PREVIEW-3`.

**Comment by rolivieri** [comment]
@youming-lin Is this still a valid issue? Are you using a preview version in any of our projects? We were under the impression that only development and release versions were used in our projects. Let us know if this is not the case.

**Comment by youming-lin** [comment]
@rolivieri I was using preview versions when checking for possible issues in our code before the GM versions are released. It's not a must-have, only a nice-to-have.

Closing issue.

**Comment by rolivieri** [comment]
@youming-lin Got you, we can keep this issue open and add it to the backlog with a low priority if you'd like.

**Comment by youming-lin** [comment]
@rolivieri Sure, if it's something that you think might be worked on in the future.

**Comment by rolivieri** [comment]
@youming-lin Cool, we could tackle it at some point when items of higher priority are taken care and/or if there is an urgent need for it. I just reopened it, thanks!

**Comment by youming-lin** [comment]
Updated title to encompass all PREVIEW toolchains, not just 3.0.1-PREVIEW.

This issue will potentially be revisited if we decide to expand test coverage of repos on more Swift versions (i.e., n-1, n, n+1) in order to catch bugs before the next Swift version drops.

**Comment by ianpartridge** [comment]
Swift.org are no longer publishing PREVIEW builds, just nightlies.  So I think this is no longer needed.
