### ISSUE TITLE
No support for custom test command

### ISSUE THREAD

**Issue by philipce** [IBM-Swift/Package-Builder#81]
Looks like `run_tests.sh` is hard coded to run `swift test`... it would be nice if there were support for custom test commands, e.g. for a `.swift-test-platform` file analogous to what exists for `.swift-build-platform`. My use case was running tests for a package that needs to add to the library link search path.

**Comment by christiancompton** [comment]
Hi @philipce - Can you give me an example of the custom `swift test` command that you would be running?

**Comment by philipce** [comment]
Sure! For example I've installed the openBLAS library in a place that's not on my search path, so need to pass a flag to the linker. I can build with `swift build -L/usr/local/opt/openblas/lib -lopenblas`, but running `swift test` has linker issues since it can't find openBLAS. Testing with `swift test -L/usr/local/opt/openblas/lib -lopenblas`solves the problem.

**Comment by rolivieri** [comment]
This change is now in develop branch. We will be merging with master soon. Closing issue.
